// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: console/console.proto

package console

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_console_console_proto protoreflect.FileDescriptor

const file_console_console_proto_rawDesc = "" +
	"\n" +
	"\x15console/console.proto\x12\vapi.console\x1a\x1copenapi/v3/annotations.proto2\t\n" +
	"\aConsoleB\xc3\x02\xbaG\xf9\x01\x12\xc1\x01\n" +
	"\x15Go-Kratos Console API\x12 Management console for Go-Kratos\"6\n" +
	"\x06Sendya\x12\x19https://github.com/sendya\x1a\x11yladmxa@gmail.com*G\n" +
	"\x0eApache License\x125https://github.com/google/gnostic/blob/master/LICENSE2\x051.0.0*3:1\n" +
	"/\n" +
	"\n" +
	"ApiKeyAuth\x12!\n" +
	"\x1f\n" +
	"\x06apiKey\x1a\rAuthorization\"\x06header\n" +
	"\vapi.consoleP\x01Z5github.com/omalloc/kratos-console/api/console;consoleb\x06proto3"

var file_console_console_proto_goTypes = []any{}
var file_console_console_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_console_console_proto_init() }
func file_console_console_proto_init() {
	if File_console_console_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_console_proto_rawDesc), len(file_console_console_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_console_proto_goTypes,
		DependencyIndexes: file_console_console_proto_depIdxs,
	}.Build()
	File_console_console_proto = out.File
	file_console_console_proto_goTypes = nil
	file_console_console_proto_depIdxs = nil
}
