// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: console/administration/menu.proto

package administration

import (
	protobuf "github.com/omalloc/contrib/protobuf"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuStatus int32

const (
	MenuStatus_MenuStatus_ENABLE  MenuStatus = 0
	MenuStatus_MenuStatus_DISABLE MenuStatus = 1
)

// Enum value maps for MenuStatus.
var (
	MenuStatus_name = map[int32]string{
		0: "MenuStatus_ENABLE",
		1: "MenuStatus_DISABLE",
	}
	MenuStatus_value = map[string]int32{
		"MenuStatus_ENABLE":  0,
		"MenuStatus_DISABLE": 1,
	}
)

func (x MenuStatus) Enum() *MenuStatus {
	p := new(MenuStatus)
	*p = x
	return p
}

func (x MenuStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MenuStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_console_administration_menu_proto_enumTypes[0].Descriptor()
}

func (MenuStatus) Type() protoreflect.EnumType {
	return &file_console_administration_menu_proto_enumTypes[0]
}

func (x MenuStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MenuStatus.Descriptor instead.
func (MenuStatus) EnumDescriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{0}
}

type MenuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	PermissionId  int64                  `protobuf:"varint,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	SortBy        int64                  `protobuf:"varint,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Hidden        bool                   `protobuf:"varint,8,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Status        MenuStatus             `protobuf:"varint,9,opt,name=status,proto3,enum=api.console.administration.MenuStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuInfo) Reset() {
	*x = MenuInfo{}
	mi := &file_console_administration_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuInfo) ProtoMessage() {}

func (x *MenuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuInfo.ProtoReflect.Descriptor instead.
func (*MenuInfo) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuInfo) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MenuInfo) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *MenuInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuInfo) GetSortBy() int64 {
	if x != nil {
		return x.SortBy
	}
	return 0
}

func (x *MenuInfo) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *MenuInfo) GetStatus() MenuStatus {
	if x != nil {
		return x.Status
	}
	return MenuStatus_MenuStatus_ENABLE
}

func (x *MenuInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MenuInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	PermissionId  int64                  `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	SortBy        int64                  `protobuf:"varint,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Hidden        bool                   `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Status        MenuStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=api.console.administration.MenuStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuRequest) Reset() {
	*x = CreateMenuRequest{}
	mi := &file_console_administration_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuRequest) ProtoMessage() {}

func (x *CreateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMenuRequest) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CreateMenuRequest) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *CreateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateMenuRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateMenuRequest) GetSortBy() int64 {
	if x != nil {
		return x.SortBy
	}
	return 0
}

func (x *CreateMenuRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *CreateMenuRequest) GetStatus() MenuStatus {
	if x != nil {
		return x.Status
	}
	return MenuStatus_MenuStatus_ENABLE
}

type CreateMenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuReply) Reset() {
	*x = CreateMenuReply{}
	mi := &file_console_administration_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuReply) ProtoMessage() {}

func (x *CreateMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuReply.ProtoReflect.Descriptor instead.
func (*CreateMenuReply) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMenuReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	PermissionId  int64                  `protobuf:"varint,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	SortBy        int64                  `protobuf:"varint,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Hidden        bool                   `protobuf:"varint,8,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Status        MenuStatus             `protobuf:"varint,9,opt,name=status,proto3,enum=api.console.administration.MenuStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuRequest) Reset() {
	*x = UpdateMenuRequest{}
	mi := &file_console_administration_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuRequest) ProtoMessage() {}

func (x *UpdateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMenuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMenuRequest) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UpdateMenuRequest) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *UpdateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateMenuRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMenuRequest) GetSortBy() int64 {
	if x != nil {
		return x.SortBy
	}
	return 0
}

func (x *UpdateMenuRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *UpdateMenuRequest) GetStatus() MenuStatus {
	if x != nil {
		return x.Status
	}
	return MenuStatus_MenuStatus_ENABLE
}

type UpdateMenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuReply) Reset() {
	*x = UpdateMenuReply{}
	mi := &file_console_administration_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuReply) ProtoMessage() {}

func (x *UpdateMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuReply.ProtoReflect.Descriptor instead.
func (*UpdateMenuReply) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{4}
}

type DeleteMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuRequest) Reset() {
	*x = DeleteMenuRequest{}
	mi := &file_console_administration_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuRequest) ProtoMessage() {}

func (x *DeleteMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMenuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuReply) Reset() {
	*x = DeleteMenuReply{}
	mi := &file_console_administration_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuReply) ProtoMessage() {}

func (x *DeleteMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuReply.ProtoReflect.Descriptor instead.
func (*DeleteMenuReply) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{6}
}

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_console_administration_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{7}
}

func (x *GetMenuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *MenuInfo              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuReply) Reset() {
	*x = GetMenuReply{}
	mi := &file_console_administration_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuReply) ProtoMessage() {}

func (x *GetMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuReply.ProtoReflect.Descriptor instead.
func (*GetMenuReply) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{8}
}

func (x *GetMenuReply) GetData() *MenuInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        MenuStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=api.console.administration.MenuStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuRequest) Reset() {
	*x = ListMenuRequest{}
	mi := &file_console_administration_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuRequest) ProtoMessage() {}

func (x *ListMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuRequest.ProtoReflect.Descriptor instead.
func (*ListMenuRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{9}
}

func (x *ListMenuRequest) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListMenuRequest) GetStatus() MenuStatus {
	if x != nil {
		return x.Status
	}
	return MenuStatus_MenuStatus_ENABLE
}

type ListMenuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MenuInfo            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuReply) Reset() {
	*x = ListMenuReply{}
	mi := &file_console_administration_menu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuReply) ProtoMessage() {}

func (x *ListMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_menu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuReply.ProtoReflect.Descriptor instead.
func (*ListMenuReply) Descriptor() ([]byte, []int) {
	return file_console_administration_menu_proto_rawDescGZIP(), []int{10}
}

func (x *ListMenuReply) GetData() []*MenuInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListMenuReply) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_console_administration_menu_proto protoreflect.FileDescriptor

const file_console_administration_menu_proto_rawDesc = "" +
	"\n" +
	"!console/administration/menu.proto\x12\x1aapi.console.administration\x1a\x1cgoogle/api/annotations.proto\x1a\x19protobuf/pagination.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x02\n" +
	"\bMenuInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\x03R\fpermissionId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x17\n" +
	"\asort_by\x18\a \x01(\x03R\x06sortBy\x12\x16\n" +
	"\x06hidden\x18\b \x01(\bR\x06hidden\x12>\n" +
	"\x06status\x18\t \x01(\x0e2&.api.console.administration.MenuStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf7\x01\n" +
	"\x11CreateMenuRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\x03R\fpermissionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\x03R\x06sortBy\x12\x16\n" +
	"\x06hidden\x18\a \x01(\bR\x06hidden\x12>\n" +
	"\x06status\x18\b \x01(\x0e2&.api.console.administration.MenuStatusR\x06status\"!\n" +
	"\x0fCreateMenuReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x87\x02\n" +
	"\x11UpdateMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\x03R\fpermissionId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x17\n" +
	"\asort_by\x18\a \x01(\x03R\x06sortBy\x12\x16\n" +
	"\x06hidden\x18\b \x01(\bR\x06hidden\x12>\n" +
	"\x06status\x18\t \x01(\x0e2&.api.console.administration.MenuStatusR\x06status\"\x11\n" +
	"\x0fUpdateMenuReply\"#\n" +
	"\x11DeleteMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteMenuReply\" \n" +
	"\x0eGetMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\fGetMenuReply\x128\n" +
	"\x04data\x18\x01 \x01(\v2$.api.console.administration.MenuInfoR\x04data\"\x9b\x01\n" +
	"\x0fListMenuRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.api.console.administration.MenuStatusR\x06status\"\x7f\n" +
	"\rListMenuReply\x128\n" +
	"\x04data\x18\x01 \x03(\v2$.api.console.administration.MenuInfoR\x04data\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination*;\n" +
	"\n" +
	"MenuStatus\x12\x15\n" +
	"\x11MenuStatus_ENABLE\x10\x00\x12\x16\n" +
	"\x12MenuStatus_DISABLE\x10\x012\xa8\x05\n" +
	"\x04Menu\x12\x86\x01\n" +
	"\n" +
	"CreateMenu\x12-.api.console.administration.CreateMenuRequest\x1a+.api.console.administration.CreateMenuReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/console/menu\x12\x8b\x01\n" +
	"\n" +
	"UpdateMenu\x12-.api.console.administration.UpdateMenuRequest\x1a+.api.console.administration.UpdateMenuReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/console/menu/{id}\x12\x88\x01\n" +
	"\n" +
	"DeleteMenu\x12-.api.console.administration.DeleteMenuRequest\x1a+.api.console.administration.DeleteMenuReply\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/console/menu/{id}\x12\x7f\n" +
	"\aGetMenu\x12*.api.console.administration.GetMenuRequest\x1a(.api.console.administration.GetMenuReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/console/menu/{id}\x12}\n" +
	"\bListMenu\x12+.api.console.administration.ListMenuRequest\x1a).api.console.administration.ListMenuReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/console/menuBi\n" +
	"\x1aapi.console.administrationP\x01ZIgithub.com/omalloc/kratos-admin/api/console/administration;administrationb\x06proto3"

var (
	file_console_administration_menu_proto_rawDescOnce sync.Once
	file_console_administration_menu_proto_rawDescData []byte
)

func file_console_administration_menu_proto_rawDescGZIP() []byte {
	file_console_administration_menu_proto_rawDescOnce.Do(func() {
		file_console_administration_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_administration_menu_proto_rawDesc), len(file_console_administration_menu_proto_rawDesc)))
	})
	return file_console_administration_menu_proto_rawDescData
}

var file_console_administration_menu_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_console_administration_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_console_administration_menu_proto_goTypes = []any{
	(MenuStatus)(0),               // 0: api.console.administration.MenuStatus
	(*MenuInfo)(nil),              // 1: api.console.administration.MenuInfo
	(*CreateMenuRequest)(nil),     // 2: api.console.administration.CreateMenuRequest
	(*CreateMenuReply)(nil),       // 3: api.console.administration.CreateMenuReply
	(*UpdateMenuRequest)(nil),     // 4: api.console.administration.UpdateMenuRequest
	(*UpdateMenuReply)(nil),       // 5: api.console.administration.UpdateMenuReply
	(*DeleteMenuRequest)(nil),     // 6: api.console.administration.DeleteMenuRequest
	(*DeleteMenuReply)(nil),       // 7: api.console.administration.DeleteMenuReply
	(*GetMenuRequest)(nil),        // 8: api.console.administration.GetMenuRequest
	(*GetMenuReply)(nil),          // 9: api.console.administration.GetMenuReply
	(*ListMenuRequest)(nil),       // 10: api.console.administration.ListMenuRequest
	(*ListMenuReply)(nil),         // 11: api.console.administration.ListMenuReply
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*protobuf.Pagination)(nil),   // 13: protobuf.Pagination
}
var file_console_administration_menu_proto_depIdxs = []int32{
	0,  // 0: api.console.administration.MenuInfo.status:type_name -> api.console.administration.MenuStatus
	12, // 1: api.console.administration.MenuInfo.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: api.console.administration.MenuInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: api.console.administration.CreateMenuRequest.status:type_name -> api.console.administration.MenuStatus
	0,  // 4: api.console.administration.UpdateMenuRequest.status:type_name -> api.console.administration.MenuStatus
	1,  // 5: api.console.administration.GetMenuReply.data:type_name -> api.console.administration.MenuInfo
	13, // 6: api.console.administration.ListMenuRequest.pagination:type_name -> protobuf.Pagination
	0,  // 7: api.console.administration.ListMenuRequest.status:type_name -> api.console.administration.MenuStatus
	1,  // 8: api.console.administration.ListMenuReply.data:type_name -> api.console.administration.MenuInfo
	13, // 9: api.console.administration.ListMenuReply.pagination:type_name -> protobuf.Pagination
	2,  // 10: api.console.administration.Menu.CreateMenu:input_type -> api.console.administration.CreateMenuRequest
	4,  // 11: api.console.administration.Menu.UpdateMenu:input_type -> api.console.administration.UpdateMenuRequest
	6,  // 12: api.console.administration.Menu.DeleteMenu:input_type -> api.console.administration.DeleteMenuRequest
	8,  // 13: api.console.administration.Menu.GetMenu:input_type -> api.console.administration.GetMenuRequest
	10, // 14: api.console.administration.Menu.ListMenu:input_type -> api.console.administration.ListMenuRequest
	3,  // 15: api.console.administration.Menu.CreateMenu:output_type -> api.console.administration.CreateMenuReply
	5,  // 16: api.console.administration.Menu.UpdateMenu:output_type -> api.console.administration.UpdateMenuReply
	7,  // 17: api.console.administration.Menu.DeleteMenu:output_type -> api.console.administration.DeleteMenuReply
	9,  // 18: api.console.administration.Menu.GetMenu:output_type -> api.console.administration.GetMenuReply
	11, // 19: api.console.administration.Menu.ListMenu:output_type -> api.console.administration.ListMenuReply
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_console_administration_menu_proto_init() }
func file_console_administration_menu_proto_init() {
	if File_console_administration_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_administration_menu_proto_rawDesc), len(file_console_administration_menu_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_administration_menu_proto_goTypes,
		DependencyIndexes: file_console_administration_menu_proto_depIdxs,
		EnumInfos:         file_console_administration_menu_proto_enumTypes,
		MessageInfos:      file_console_administration_menu_proto_msgTypes,
	}.Build()
	File_console_administration_menu_proto = out.File
	file_console_administration_menu_proto_goTypes = nil
	file_console_administration_menu_proto_depIdxs = nil
}
