// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: console/administration/permission.proto

package administration

import (
	protobuf "github.com/omalloc/contrib/protobuf"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionStatus int32

const (
	PermissionStatus_PERMISSION_STATUS_UNSPECIFIED PermissionStatus = 0
	PermissionStatus_PERMISSION_STATUS_ENABLED     PermissionStatus = 1
	PermissionStatus_PERMISSION_STATUS_DISABLED    PermissionStatus = 2
)

// Enum value maps for PermissionStatus.
var (
	PermissionStatus_name = map[int32]string{
		0: "PERMISSION_STATUS_UNSPECIFIED",
		1: "PERMISSION_STATUS_ENABLED",
		2: "PERMISSION_STATUS_DISABLED",
	}
	PermissionStatus_value = map[string]int32{
		"PERMISSION_STATUS_UNSPECIFIED": 0,
		"PERMISSION_STATUS_ENABLED":     1,
		"PERMISSION_STATUS_DISABLED":    2,
	}
)

func (x PermissionStatus) Enum() *PermissionStatus {
	p := new(PermissionStatus)
	*p = x
	return p
}

func (x PermissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_console_administration_permission_proto_enumTypes[0].Descriptor()
}

func (PermissionStatus) Type() protoreflect.EnumType {
	return &file_console_administration_permission_proto_enumTypes[0]
}

func (x PermissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionStatus.Descriptor instead.
func (PermissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{0}
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Describe      string                 `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"`
	Checked       bool                   `protobuf:"varint,3,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_console_administration_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Action) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *Action) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Describe      string                 `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"`
	Actions       []*Action              `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        PermissionStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=api.console.administration.PermissionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_console_administration_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *PermissionInfo) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *PermissionInfo) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PermissionInfo) GetStatus() PermissionStatus {
	if x != nil {
		return x.Status
	}
	return PermissionStatus_PERMISSION_STATUS_UNSPECIFIED
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Describe      string                 `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	Actions       []*Action              `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        PermissionStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=api.console.administration.PermissionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_console_administration_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *CreatePermissionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreatePermissionRequest) GetStatus() PermissionStatus {
	if x != nil {
		return x.Status
	}
	return PermissionStatus_PERMISSION_STATUS_UNSPECIFIED
}

type CreatePermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionReply) Reset() {
	*x = CreatePermissionReply{}
	mi := &file_console_administration_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionReply) ProtoMessage() {}

func (x *CreatePermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionReply.ProtoReflect.Descriptor instead.
func (*CreatePermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{3}
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Describe      string                 `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"`
	Actions       []*Action              `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        PermissionStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=api.console.administration.PermissionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_console_administration_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *UpdatePermissionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *UpdatePermissionRequest) GetStatus() PermissionStatus {
	if x != nil {
		return x.Status
	}
	return PermissionStatus_PERMISSION_STATUS_UNSPECIFIED
}

type UpdatePermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionReply) Reset() {
	*x = UpdatePermissionReply{}
	mi := &file_console_administration_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionReply) ProtoMessage() {}

func (x *UpdatePermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionReply.ProtoReflect.Descriptor instead.
func (*UpdatePermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{5}
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_console_administration_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionReply) Reset() {
	*x = DeletePermissionReply{}
	mi := &file_console_administration_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionReply) ProtoMessage() {}

func (x *DeletePermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionReply.ProtoReflect.Descriptor instead.
func (*DeletePermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{7}
}

type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_console_administration_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{8}
}

func (x *GetPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Describe      string                 `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"`
	Actions       []*Action              `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        PermissionStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=api.console.administration.PermissionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionReply) Reset() {
	*x = GetPermissionReply{}
	mi := &file_console_administration_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionReply) ProtoMessage() {}

func (x *GetPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionReply.ProtoReflect.Descriptor instead.
func (*GetPermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{9}
}

func (x *GetPermissionReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPermissionReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPermissionReply) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *GetPermissionReply) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *GetPermissionReply) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GetPermissionReply) GetStatus() PermissionStatus {
	if x != nil {
		return x.Status
	}
	return PermissionStatus_PERMISSION_STATUS_UNSPECIFIED
}

type ListPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Status        PermissionStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=api.console.administration.PermissionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionRequest) Reset() {
	*x = ListPermissionRequest{}
	mi := &file_console_administration_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionRequest) ProtoMessage() {}

func (x *ListPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{10}
}

func (x *ListPermissionRequest) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPermissionRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ListPermissionRequest) GetStatus() PermissionStatus {
	if x != nil {
		return x.Status
	}
	return PermissionStatus_PERMISSION_STATUS_UNSPECIFIED
}

type ListPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*PermissionInfo      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionReply) Reset() {
	*x = ListPermissionReply{}
	mi := &file_console_administration_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionReply) ProtoMessage() {}

func (x *ListPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionReply.ProtoReflect.Descriptor instead.
func (*ListPermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{11}
}

func (x *ListPermissionReply) GetData() []*PermissionInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPermissionReply) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAllPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPermissionRequest) Reset() {
	*x = ListAllPermissionRequest{}
	mi := &file_console_administration_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPermissionRequest) ProtoMessage() {}

func (x *ListAllPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPermissionRequest.ProtoReflect.Descriptor instead.
func (*ListAllPermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{12}
}

type ListAllPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*PermissionInfo      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPermissionReply) Reset() {
	*x = ListAllPermissionReply{}
	mi := &file_console_administration_permission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPermissionReply) ProtoMessage() {}

func (x *ListAllPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_permission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPermissionReply.ProtoReflect.Descriptor instead.
func (*ListAllPermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_permission_proto_rawDescGZIP(), []int{13}
}

func (x *ListAllPermissionReply) GetData() []*PermissionInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_console_administration_permission_proto protoreflect.FileDescriptor

const file_console_administration_permission_proto_rawDesc = "" +
	"\n" +
	"'console/administration/permission.proto\x12\x1aapi.console.administration\x1a\x1cgoogle/api/annotations.proto\x1a\x19protobuf/pagination.proto\"P\n" +
	"\x06Action\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bdescribe\x18\x02 \x01(\tR\bdescribe\x12\x18\n" +
	"\achecked\x18\x03 \x01(\bR\achecked\"\xea\x01\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x1a\n" +
	"\bdescribe\x18\x04 \x01(\tR\bdescribe\x12<\n" +
	"\aactions\x18\x05 \x03(\v2\".api.console.administration.ActionR\aactions\x12D\n" +
	"\x06status\x18\x06 \x01(\x0e2,.api.console.administration.PermissionStatusR\x06status\"\xe3\x01\n" +
	"\x17CreatePermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1a\n" +
	"\bdescribe\x18\x03 \x01(\tR\bdescribe\x12<\n" +
	"\aactions\x18\x04 \x03(\v2\".api.console.administration.ActionR\aactions\x12D\n" +
	"\x06status\x18\x05 \x01(\x0e2,.api.console.administration.PermissionStatusR\x06status\"\x17\n" +
	"\x15CreatePermissionReply\"\xf3\x01\n" +
	"\x17UpdatePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x1a\n" +
	"\bdescribe\x18\x04 \x01(\tR\bdescribe\x12<\n" +
	"\aactions\x18\x05 \x03(\v2\".api.console.administration.ActionR\aactions\x12D\n" +
	"\x06status\x18\x06 \x01(\x0e2,.api.console.administration.PermissionStatusR\x06status\"\x17\n" +
	"\x15UpdatePermissionReply\")\n" +
	"\x17DeletePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15DeletePermissionReply\"&\n" +
	"\x14GetPermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xee\x01\n" +
	"\x12GetPermissionReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x1a\n" +
	"\bdescribe\x18\x04 \x01(\tR\bdescribe\x12<\n" +
	"\aactions\x18\x05 \x03(\v2\".api.console.administration.ActionR\aactions\x12D\n" +
	"\x06status\x18\x06 \x01(\x0e2,.api.console.administration.PermissionStatusR\x06status\"\xbd\x01\n" +
	"\x15ListPermissionRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12D\n" +
	"\x06status\x18\x04 \x01(\x0e2,.api.console.administration.PermissionStatusR\x06status\"\x8b\x01\n" +
	"\x13ListPermissionReply\x12>\n" +
	"\x04data\x18\x01 \x03(\v2*.api.console.administration.PermissionInfoR\x04data\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\"\x1a\n" +
	"\x18ListAllPermissionRequest\"X\n" +
	"\x16ListAllPermissionReply\x12>\n" +
	"\x04data\x18\x01 \x03(\v2*.api.console.administration.PermissionInfoR\x04data*t\n" +
	"\x10PermissionStatus\x12!\n" +
	"\x1dPERMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PERMISSION_STATUS_ENABLED\x10\x01\x12\x1e\n" +
	"\x1aPERMISSION_STATUS_DISABLED\x10\x022\xd0\a\n" +
	"\n" +
	"Permission\x12\x9e\x01\n" +
	"\x10CreatePermission\x123.api.console.administration.CreatePermissionRequest\x1a1.api.console.administration.CreatePermissionReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/console/permission\x12\xa3\x01\n" +
	"\x10UpdatePermission\x123.api.console.administration.UpdatePermissionRequest\x1a1.api.console.administration.UpdatePermissionReply\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/api/console/permission/{id}\x12\xa0\x01\n" +
	"\x10DeletePermission\x123.api.console.administration.DeletePermissionRequest\x1a1.api.console.administration.DeletePermissionReply\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/api/console/permission/{id}\x12\x97\x01\n" +
	"\rGetPermission\x120.api.console.administration.GetPermissionRequest\x1a..api.console.administration.GetPermissionReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/console/permission/{id}\x12\x95\x01\n" +
	"\x0eListPermission\x121.api.console.administration.ListPermissionRequest\x1a/.api.console.administration.ListPermissionReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/console/permission\x12\xa5\x01\n" +
	"\x11ListAllPermission\x124.api.console.administration.ListAllPermissionRequest\x1a2.api.console.administration.ListAllPermissionReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/console/permission-scopedBi\n" +
	"\x1aapi.console.administrationP\x01ZIgithub.com/omalloc/kratos-admin/api/console/administration;administrationb\x06proto3"

var (
	file_console_administration_permission_proto_rawDescOnce sync.Once
	file_console_administration_permission_proto_rawDescData []byte
)

func file_console_administration_permission_proto_rawDescGZIP() []byte {
	file_console_administration_permission_proto_rawDescOnce.Do(func() {
		file_console_administration_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_administration_permission_proto_rawDesc), len(file_console_administration_permission_proto_rawDesc)))
	})
	return file_console_administration_permission_proto_rawDescData
}

var file_console_administration_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_console_administration_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_console_administration_permission_proto_goTypes = []any{
	(PermissionStatus)(0),            // 0: api.console.administration.PermissionStatus
	(*Action)(nil),                   // 1: api.console.administration.Action
	(*PermissionInfo)(nil),           // 2: api.console.administration.PermissionInfo
	(*CreatePermissionRequest)(nil),  // 3: api.console.administration.CreatePermissionRequest
	(*CreatePermissionReply)(nil),    // 4: api.console.administration.CreatePermissionReply
	(*UpdatePermissionRequest)(nil),  // 5: api.console.administration.UpdatePermissionRequest
	(*UpdatePermissionReply)(nil),    // 6: api.console.administration.UpdatePermissionReply
	(*DeletePermissionRequest)(nil),  // 7: api.console.administration.DeletePermissionRequest
	(*DeletePermissionReply)(nil),    // 8: api.console.administration.DeletePermissionReply
	(*GetPermissionRequest)(nil),     // 9: api.console.administration.GetPermissionRequest
	(*GetPermissionReply)(nil),       // 10: api.console.administration.GetPermissionReply
	(*ListPermissionRequest)(nil),    // 11: api.console.administration.ListPermissionRequest
	(*ListPermissionReply)(nil),      // 12: api.console.administration.ListPermissionReply
	(*ListAllPermissionRequest)(nil), // 13: api.console.administration.ListAllPermissionRequest
	(*ListAllPermissionReply)(nil),   // 14: api.console.administration.ListAllPermissionReply
	(*protobuf.Pagination)(nil),      // 15: protobuf.Pagination
}
var file_console_administration_permission_proto_depIdxs = []int32{
	1,  // 0: api.console.administration.PermissionInfo.actions:type_name -> api.console.administration.Action
	0,  // 1: api.console.administration.PermissionInfo.status:type_name -> api.console.administration.PermissionStatus
	1,  // 2: api.console.administration.CreatePermissionRequest.actions:type_name -> api.console.administration.Action
	0,  // 3: api.console.administration.CreatePermissionRequest.status:type_name -> api.console.administration.PermissionStatus
	1,  // 4: api.console.administration.UpdatePermissionRequest.actions:type_name -> api.console.administration.Action
	0,  // 5: api.console.administration.UpdatePermissionRequest.status:type_name -> api.console.administration.PermissionStatus
	1,  // 6: api.console.administration.GetPermissionReply.actions:type_name -> api.console.administration.Action
	0,  // 7: api.console.administration.GetPermissionReply.status:type_name -> api.console.administration.PermissionStatus
	15, // 8: api.console.administration.ListPermissionRequest.pagination:type_name -> protobuf.Pagination
	0,  // 9: api.console.administration.ListPermissionRequest.status:type_name -> api.console.administration.PermissionStatus
	2,  // 10: api.console.administration.ListPermissionReply.data:type_name -> api.console.administration.PermissionInfo
	15, // 11: api.console.administration.ListPermissionReply.pagination:type_name -> protobuf.Pagination
	2,  // 12: api.console.administration.ListAllPermissionReply.data:type_name -> api.console.administration.PermissionInfo
	3,  // 13: api.console.administration.Permission.CreatePermission:input_type -> api.console.administration.CreatePermissionRequest
	5,  // 14: api.console.administration.Permission.UpdatePermission:input_type -> api.console.administration.UpdatePermissionRequest
	7,  // 15: api.console.administration.Permission.DeletePermission:input_type -> api.console.administration.DeletePermissionRequest
	9,  // 16: api.console.administration.Permission.GetPermission:input_type -> api.console.administration.GetPermissionRequest
	11, // 17: api.console.administration.Permission.ListPermission:input_type -> api.console.administration.ListPermissionRequest
	13, // 18: api.console.administration.Permission.ListAllPermission:input_type -> api.console.administration.ListAllPermissionRequest
	4,  // 19: api.console.administration.Permission.CreatePermission:output_type -> api.console.administration.CreatePermissionReply
	6,  // 20: api.console.administration.Permission.UpdatePermission:output_type -> api.console.administration.UpdatePermissionReply
	8,  // 21: api.console.administration.Permission.DeletePermission:output_type -> api.console.administration.DeletePermissionReply
	10, // 22: api.console.administration.Permission.GetPermission:output_type -> api.console.administration.GetPermissionReply
	12, // 23: api.console.administration.Permission.ListPermission:output_type -> api.console.administration.ListPermissionReply
	14, // 24: api.console.administration.Permission.ListAllPermission:output_type -> api.console.administration.ListAllPermissionReply
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_console_administration_permission_proto_init() }
func file_console_administration_permission_proto_init() {
	if File_console_administration_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_administration_permission_proto_rawDesc), len(file_console_administration_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_administration_permission_proto_goTypes,
		DependencyIndexes: file_console_administration_permission_proto_depIdxs,
		EnumInfos:         file_console_administration_permission_proto_enumTypes,
		MessageInfos:      file_console_administration_permission_proto_msgTypes,
	}.Build()
	File_console_administration_permission_proto = out.File
	file_console_administration_permission_proto_goTypes = nil
	file_console_administration_permission_proto_depIdxs = nil
}
