// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: console/administration/role.proto

package administration

import (
	protobuf "github.com/omalloc/contrib/protobuf"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RolePermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 业务id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 角色id
	RoleId int64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// 权限id
	PermId int64 `protobuf:"varint,3,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	// 操作权限
	Actions []*Action `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	// 数据权限
	DataAccess []*Action `protobuf:"bytes,5,rep,name=data_access,json=dataAccess,proto3" json:"data_access,omitempty"`
	// 绑定权限时间
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermission) Reset() {
	*x = RolePermission{}
	mi := &file_console_administration_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermission) ProtoMessage() {}

func (x *RolePermission) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermission.ProtoReflect.Descriptor instead.
func (*RolePermission) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{0}
}

func (x *RolePermission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RolePermission) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePermission) GetPermId() int64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *RolePermission) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RolePermission) GetDataAccess() []*Action {
	if x != nil {
		return x.DataAccess
	}
	return nil
}

func (x *RolePermission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Describe      string                 `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Permissions   []*RolePermission      `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_console_administration_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RoleInfo) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *RoleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleInfo) GetPermissions() []*RolePermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Describe      string                 `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *CreateRoleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateRoleRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CreateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReply) Reset() {
	*x = CreateRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReply) ProtoMessage() {}

func (x *CreateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReply.ProtoReflect.Descriptor instead.
func (*CreateRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{3}
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Describe      string                 `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Alias         string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *UpdateRoleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateRoleRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type UpdateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReply) Reset() {
	*x = UpdateRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReply) ProtoMessage() {}

func (x *UpdateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReply.ProtoReflect.Descriptor instead.
func (*UpdateRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{5}
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReply) Reset() {
	*x = DeleteRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReply) ProtoMessage() {}

func (x *DeleteRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReply.ProtoReflect.Descriptor instead.
func (*DeleteRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{7}
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Describe      string                 `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Permissions   []*RolePermission      `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Actions       []*Action              `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	DataAccess    []*Action              `protobuf:"bytes,8,rep,name=data_access,json=dataAccess,proto3" json:"data_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleReply) Reset() {
	*x = GetRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleReply) ProtoMessage() {}

func (x *GetRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleReply.ProtoReflect.Descriptor instead.
func (*GetRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoleReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRoleReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRoleReply) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *GetRoleReply) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *GetRoleReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRoleReply) GetPermissions() []*RolePermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetRoleReply) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GetRoleReply) GetDataAccess() []*Action {
	if x != nil {
		return x.DataAccess
	}
	return nil
}

type ListRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoleRequest) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data          []*RoleInfo            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleReply) Reset() {
	*x = ListRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleReply) ProtoMessage() {}

func (x *ListRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleReply.ProtoReflect.Descriptor instead.
func (*ListRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{11}
}

func (x *ListRoleReply) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRoleReply) GetData() []*RoleInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type BindPermissionRequest struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Id            int64                                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []*BindPermissionRequest_BindPermissionBody `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPermissionRequest) Reset() {
	*x = BindPermissionRequest{}
	mi := &file_console_administration_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPermissionRequest) ProtoMessage() {}

func (x *BindPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPermissionRequest.ProtoReflect.Descriptor instead.
func (*BindPermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{12}
}

func (x *BindPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BindPermissionRequest) GetData() []*BindPermissionRequest_BindPermissionBody {
	if x != nil {
		return x.Data
	}
	return nil
}

type BindPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPermissionReply) Reset() {
	*x = BindPermissionReply{}
	mi := &file_console_administration_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPermissionReply) ProtoMessage() {}

func (x *BindPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPermissionReply.ProtoReflect.Descriptor instead.
func (*BindPermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{13}
}

type UnbindPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PermissionId  int64                  `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindPermissionRequest) Reset() {
	*x = UnbindPermissionRequest{}
	mi := &file_console_administration_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindPermissionRequest) ProtoMessage() {}

func (x *UnbindPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindPermissionRequest.ProtoReflect.Descriptor instead.
func (*UnbindPermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{14}
}

func (x *UnbindPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnbindPermissionRequest) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

type UnbindPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindPermissionReply) Reset() {
	*x = UnbindPermissionReply{}
	mi := &file_console_administration_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindPermissionReply) ProtoMessage() {}

func (x *UnbindPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindPermissionReply.ProtoReflect.Descriptor instead.
func (*UnbindPermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{15}
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_console_administration_role_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{16}
}

type GetAllReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*RoleInfo            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	mi := &file_console_administration_role_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllReply) GetData() []*RoleInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type BindPermissionRequest_BindPermissionBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  int64                  `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Actions       []*Action              `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	DataAccess    []*Action              `protobuf:"bytes,4,rep,name=data_access,json=dataAccess,proto3" json:"data_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPermissionRequest_BindPermissionBody) Reset() {
	*x = BindPermissionRequest_BindPermissionBody{}
	mi := &file_console_administration_role_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPermissionRequest_BindPermissionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPermissionRequest_BindPermissionBody) ProtoMessage() {}

func (x *BindPermissionRequest_BindPermissionBody) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPermissionRequest_BindPermissionBody.ProtoReflect.Descriptor instead.
func (*BindPermissionRequest_BindPermissionBody) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{12, 0}
}

func (x *BindPermissionRequest_BindPermissionBody) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *BindPermissionRequest_BindPermissionBody) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *BindPermissionRequest_BindPermissionBody) GetDataAccess() []*Action {
	if x != nil {
		return x.DataAccess
	}
	return nil
}

var File_console_administration_role_proto protoreflect.FileDescriptor

const file_console_administration_role_proto_rawDesc = "" +
	"\n" +
	"!console/administration/role.proto\x12\x1aapi.console.administration\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19protobuf/pagination.proto\x1a'console/administration/permission.proto\"\x90\x02\n" +
	"\x0eRolePermission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\x12\x17\n" +
	"\aperm_id\x18\x03 \x01(\x03R\x06permId\x12<\n" +
	"\aactions\x18\x04 \x03(\v2\".api.console.administration.ActionR\aactions\x12C\n" +
	"\vdata_access\x18\x05 \x03(\v2\".api.console.administration.ActionR\n" +
	"dataAccess\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc6\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x1a\n" +
	"\bdescribe\x18\x04 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12L\n" +
	"\vpermissions\x18\x06 \x03(\v2*.api.console.administration.RolePermissionR\vpermissions\"q\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdescribe\x18\x02 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\"\x11\n" +
	"\x0fCreateRoleReply\"\x81\x01\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdescribe\x18\x03 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\"\x11\n" +
	"\x0fUpdateRoleReply\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteRoleReply\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xcd\x02\n" +
	"\fGetRoleReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x1a\n" +
	"\bdescribe\x18\x04 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12L\n" +
	"\vpermissions\x18\x06 \x03(\v2*.api.console.administration.RolePermissionR\vpermissions\x12<\n" +
	"\aactions\x18\a \x03(\v2\".api.console.administration.ActionR\aactions\x12C\n" +
	"\vdata_access\x18\b \x03(\v2\".api.console.administration.ActionR\n" +
	"dataAccess\"G\n" +
	"\x0fListRoleRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\"\x7f\n" +
	"\rListRoleReply\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\x128\n" +
	"\x04data\x18\x02 \x03(\v2$.api.console.administration.RoleInfoR\x04data\"\xc0\x02\n" +
	"\x15BindPermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12X\n" +
	"\x04data\x18\x02 \x03(\v2D.api.console.administration.BindPermissionRequest.BindPermissionBodyR\x04data\x1a\xbc\x01\n" +
	"\x12BindPermissionBody\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\x03R\fpermissionId\x12<\n" +
	"\aactions\x18\x03 \x03(\v2\".api.console.administration.ActionR\aactions\x12C\n" +
	"\vdata_access\x18\x04 \x03(\v2\".api.console.administration.ActionR\n" +
	"dataAccess\"\x15\n" +
	"\x13BindPermissionReply\"N\n" +
	"\x17UnbindPermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\x03R\fpermissionId\"\x17\n" +
	"\x15UnbindPermissionReply\"\x0f\n" +
	"\rGetAllRequest\"G\n" +
	"\vGetAllReply\x128\n" +
	"\x04data\x18\x01 \x03(\v2$.api.console.administration.RoleInfoR\x04data2\x85\t\n" +
	"\x04Role\x12\x86\x01\n" +
	"\n" +
	"CreateRole\x12-.api.console.administration.CreateRoleRequest\x1a+.api.console.administration.CreateRoleReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/console/role\x12\x8b\x01\n" +
	"\n" +
	"UpdateRole\x12-.api.console.administration.UpdateRoleRequest\x1a+.api.console.administration.UpdateRoleReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/console/role/{id}\x12\x88\x01\n" +
	"\n" +
	"DeleteRole\x12-.api.console.administration.DeleteRoleRequest\x1a+.api.console.administration.DeleteRoleReply\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/console/role/{id}\x12\x7f\n" +
	"\aGetRole\x12*.api.console.administration.GetRoleRequest\x1a(.api.console.administration.GetRoleReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/console/role/{id}\x12}\n" +
	"\bListRole\x12+.api.console.administration.ListRoleRequest\x1a).api.console.administration.ListRoleReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/console/role\x12\xa2\x01\n" +
	"\x0eBindPermission\x121.api.console.administration.BindPermissionRequest\x1a/.api.console.administration.BindPermissionReply\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/console/role/{id}/permission\x12\xb8\x01\n" +
	"\x10UnbindPermission\x123.api.console.administration.UnbindPermissionRequest\x1a1.api.console.administration.UnbindPermissionReply\"<\x82\xd3\xe4\x93\x026:\x01*\x1a1/api/console/role/{id}/permission/{permission_id}\x12{\n" +
	"\x06GetAll\x12).api.console.administration.GetAllRequest\x1a'.api.console.administration.GetAllReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/console/role-allBi\n" +
	"\x1aapi.console.administrationP\x01ZIgithub.com/omalloc/kratos-admin/api/console/administration;administrationb\x06proto3"

var (
	file_console_administration_role_proto_rawDescOnce sync.Once
	file_console_administration_role_proto_rawDescData []byte
)

func file_console_administration_role_proto_rawDescGZIP() []byte {
	file_console_administration_role_proto_rawDescOnce.Do(func() {
		file_console_administration_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_administration_role_proto_rawDesc), len(file_console_administration_role_proto_rawDesc)))
	})
	return file_console_administration_role_proto_rawDescData
}

var file_console_administration_role_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_console_administration_role_proto_goTypes = []any{
	(*RolePermission)(nil),                           // 0: api.console.administration.RolePermission
	(*RoleInfo)(nil),                                 // 1: api.console.administration.RoleInfo
	(*CreateRoleRequest)(nil),                        // 2: api.console.administration.CreateRoleRequest
	(*CreateRoleReply)(nil),                          // 3: api.console.administration.CreateRoleReply
	(*UpdateRoleRequest)(nil),                        // 4: api.console.administration.UpdateRoleRequest
	(*UpdateRoleReply)(nil),                          // 5: api.console.administration.UpdateRoleReply
	(*DeleteRoleRequest)(nil),                        // 6: api.console.administration.DeleteRoleRequest
	(*DeleteRoleReply)(nil),                          // 7: api.console.administration.DeleteRoleReply
	(*GetRoleRequest)(nil),                           // 8: api.console.administration.GetRoleRequest
	(*GetRoleReply)(nil),                             // 9: api.console.administration.GetRoleReply
	(*ListRoleRequest)(nil),                          // 10: api.console.administration.ListRoleRequest
	(*ListRoleReply)(nil),                            // 11: api.console.administration.ListRoleReply
	(*BindPermissionRequest)(nil),                    // 12: api.console.administration.BindPermissionRequest
	(*BindPermissionReply)(nil),                      // 13: api.console.administration.BindPermissionReply
	(*UnbindPermissionRequest)(nil),                  // 14: api.console.administration.UnbindPermissionRequest
	(*UnbindPermissionReply)(nil),                    // 15: api.console.administration.UnbindPermissionReply
	(*GetAllRequest)(nil),                            // 16: api.console.administration.GetAllRequest
	(*GetAllReply)(nil),                              // 17: api.console.administration.GetAllReply
	(*BindPermissionRequest_BindPermissionBody)(nil), // 18: api.console.administration.BindPermissionRequest.BindPermissionBody
	(*Action)(nil),                                   // 19: api.console.administration.Action
	(*timestamppb.Timestamp)(nil),                    // 20: google.protobuf.Timestamp
	(*protobuf.Pagination)(nil),                      // 21: protobuf.Pagination
}
var file_console_administration_role_proto_depIdxs = []int32{
	19, // 0: api.console.administration.RolePermission.actions:type_name -> api.console.administration.Action
	19, // 1: api.console.administration.RolePermission.data_access:type_name -> api.console.administration.Action
	20, // 2: api.console.administration.RolePermission.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: api.console.administration.RoleInfo.permissions:type_name -> api.console.administration.RolePermission
	0,  // 4: api.console.administration.GetRoleReply.permissions:type_name -> api.console.administration.RolePermission
	19, // 5: api.console.administration.GetRoleReply.actions:type_name -> api.console.administration.Action
	19, // 6: api.console.administration.GetRoleReply.data_access:type_name -> api.console.administration.Action
	21, // 7: api.console.administration.ListRoleRequest.pagination:type_name -> protobuf.Pagination
	21, // 8: api.console.administration.ListRoleReply.pagination:type_name -> protobuf.Pagination
	1,  // 9: api.console.administration.ListRoleReply.data:type_name -> api.console.administration.RoleInfo
	18, // 10: api.console.administration.BindPermissionRequest.data:type_name -> api.console.administration.BindPermissionRequest.BindPermissionBody
	1,  // 11: api.console.administration.GetAllReply.data:type_name -> api.console.administration.RoleInfo
	19, // 12: api.console.administration.BindPermissionRequest.BindPermissionBody.actions:type_name -> api.console.administration.Action
	19, // 13: api.console.administration.BindPermissionRequest.BindPermissionBody.data_access:type_name -> api.console.administration.Action
	2,  // 14: api.console.administration.Role.CreateRole:input_type -> api.console.administration.CreateRoleRequest
	4,  // 15: api.console.administration.Role.UpdateRole:input_type -> api.console.administration.UpdateRoleRequest
	6,  // 16: api.console.administration.Role.DeleteRole:input_type -> api.console.administration.DeleteRoleRequest
	8,  // 17: api.console.administration.Role.GetRole:input_type -> api.console.administration.GetRoleRequest
	10, // 18: api.console.administration.Role.ListRole:input_type -> api.console.administration.ListRoleRequest
	12, // 19: api.console.administration.Role.BindPermission:input_type -> api.console.administration.BindPermissionRequest
	14, // 20: api.console.administration.Role.UnbindPermission:input_type -> api.console.administration.UnbindPermissionRequest
	16, // 21: api.console.administration.Role.GetAll:input_type -> api.console.administration.GetAllRequest
	3,  // 22: api.console.administration.Role.CreateRole:output_type -> api.console.administration.CreateRoleReply
	5,  // 23: api.console.administration.Role.UpdateRole:output_type -> api.console.administration.UpdateRoleReply
	7,  // 24: api.console.administration.Role.DeleteRole:output_type -> api.console.administration.DeleteRoleReply
	9,  // 25: api.console.administration.Role.GetRole:output_type -> api.console.administration.GetRoleReply
	11, // 26: api.console.administration.Role.ListRole:output_type -> api.console.administration.ListRoleReply
	13, // 27: api.console.administration.Role.BindPermission:output_type -> api.console.administration.BindPermissionReply
	15, // 28: api.console.administration.Role.UnbindPermission:output_type -> api.console.administration.UnbindPermissionReply
	17, // 29: api.console.administration.Role.GetAll:output_type -> api.console.administration.GetAllReply
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_console_administration_role_proto_init() }
func file_console_administration_role_proto_init() {
	if File_console_administration_role_proto != nil {
		return
	}
	file_console_administration_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_administration_role_proto_rawDesc), len(file_console_administration_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_administration_role_proto_goTypes,
		DependencyIndexes: file_console_administration_role_proto_depIdxs,
		MessageInfos:      file_console_administration_role_proto_msgTypes,
	}.Build()
	File_console_administration_role_proto = out.File
	file_console_administration_role_proto_goTypes = nil
	file_console_administration_role_proto_depIdxs = nil
}
