// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: console/administration/role.proto

package administration

import (
	protobuf "github.com/omalloc/contrib/protobuf"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Describe      string                 `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Actions       []*Action              `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	DataAccess    []*Action              `protobuf:"bytes,6,rep,name=data_access,json=dataAccess,proto3" json:"data_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_console_administration_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *RoleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleInfo) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RoleInfo) GetDataAccess() []*Action {
	if x != nil {
		return x.DataAccess
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Describe      string                 `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *CreateRoleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReply) Reset() {
	*x = CreateRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReply) ProtoMessage() {}

func (x *CreateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReply.ProtoReflect.Descriptor instead.
func (*CreateRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{2}
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Describe      string                 `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *UpdateRoleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReply) Reset() {
	*x = UpdateRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReply) ProtoMessage() {}

func (x *UpdateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReply.ProtoReflect.Descriptor instead.
func (*UpdateRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{4}
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReply) Reset() {
	*x = DeleteRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReply) ProtoMessage() {}

func (x *DeleteRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReply.ProtoReflect.Descriptor instead.
func (*DeleteRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{6}
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Describe      string                 `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Actions       []*Action              `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	DataAccess    []*Action              `protobuf:"bytes,5,rep,name=data_access,json=dataAccess,proto3" json:"data_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleReply) Reset() {
	*x = GetRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleReply) ProtoMessage() {}

func (x *GetRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleReply.ProtoReflect.Descriptor instead.
func (*GetRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRoleReply) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *GetRoleReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRoleReply) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GetRoleReply) GetDataAccess() []*Action {
	if x != nil {
		return x.DataAccess
	}
	return nil
}

type ListRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_console_administration_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoleRequest) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data          []*RoleInfo            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleReply) Reset() {
	*x = ListRoleReply{}
	mi := &file_console_administration_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleReply) ProtoMessage() {}

func (x *ListRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleReply.ProtoReflect.Descriptor instead.
func (*ListRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoleReply) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRoleReply) GetData() []*RoleInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type BindPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PermissionId  int64                  `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Actions       []*Action              `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	DataAccess    []*Action              `protobuf:"bytes,4,rep,name=data_access,json=dataAccess,proto3" json:"data_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPermissionRequest) Reset() {
	*x = BindPermissionRequest{}
	mi := &file_console_administration_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPermissionRequest) ProtoMessage() {}

func (x *BindPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPermissionRequest.ProtoReflect.Descriptor instead.
func (*BindPermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{11}
}

func (x *BindPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BindPermissionRequest) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *BindPermissionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *BindPermissionRequest) GetDataAccess() []*Action {
	if x != nil {
		return x.DataAccess
	}
	return nil
}

type BindPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPermissionReply) Reset() {
	*x = BindPermissionReply{}
	mi := &file_console_administration_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPermissionReply) ProtoMessage() {}

func (x *BindPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPermissionReply.ProtoReflect.Descriptor instead.
func (*BindPermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{12}
}

type UnbindPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PermissionId  int64                  `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindPermissionRequest) Reset() {
	*x = UnbindPermissionRequest{}
	mi := &file_console_administration_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindPermissionRequest) ProtoMessage() {}

func (x *UnbindPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindPermissionRequest.ProtoReflect.Descriptor instead.
func (*UnbindPermissionRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{13}
}

func (x *UnbindPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnbindPermissionRequest) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

type UnbindPermissionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindPermissionReply) Reset() {
	*x = UnbindPermissionReply{}
	mi := &file_console_administration_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindPermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindPermissionReply) ProtoMessage() {}

func (x *UnbindPermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindPermissionReply.ProtoReflect.Descriptor instead.
func (*UnbindPermissionReply) Descriptor() ([]byte, []int) {
	return file_console_administration_role_proto_rawDescGZIP(), []int{14}
}

var File_console_administration_role_proto protoreflect.FileDescriptor

const file_console_administration_role_proto_rawDesc = "" +
	"\n" +
	"!console/administration/role.proto\x12\x1aapi.console.administration\x1a\x1cgoogle/api/annotations.proto\x1a\x19protobuf/pagination.proto\x1a'console/administration/permission.proto\"\xe5\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdescribe\x18\x03 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12<\n" +
	"\aactions\x18\x05 \x03(\v2\".api.console.administration.ActionR\aactions\x12C\n" +
	"\vdata_access\x18\x06 \x03(\v2\".api.console.administration.ActionR\n" +
	"dataAccess\"[\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdescribe\x18\x02 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x11\n" +
	"\x0fCreateRoleReply\"k\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdescribe\x18\x03 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x11\n" +
	"\x0fUpdateRoleReply\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteRoleReply\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd9\x01\n" +
	"\fGetRoleReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdescribe\x18\x02 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12<\n" +
	"\aactions\x18\x04 \x03(\v2\".api.console.administration.ActionR\aactions\x12C\n" +
	"\vdata_access\x18\x05 \x03(\v2\".api.console.administration.ActionR\n" +
	"dataAccess\"G\n" +
	"\x0fListRoleRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\"\x7f\n" +
	"\rListRoleReply\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\x128\n" +
	"\x04data\x18\x02 \x03(\v2$.api.console.administration.RoleInfoR\x04data\"\xcf\x01\n" +
	"\x15BindPermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\x03R\fpermissionId\x12<\n" +
	"\aactions\x18\x03 \x03(\v2\".api.console.administration.ActionR\aactions\x12C\n" +
	"\vdata_access\x18\x04 \x03(\v2\".api.console.administration.ActionR\n" +
	"dataAccess\"\x15\n" +
	"\x13BindPermissionReply\"N\n" +
	"\x17UnbindPermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\x03R\fpermissionId\"\x17\n" +
	"\x15UnbindPermissionReply2\x88\b\n" +
	"\x04Role\x12\x86\x01\n" +
	"\n" +
	"CreateRole\x12-.api.console.administration.CreateRoleRequest\x1a+.api.console.administration.CreateRoleReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/console/role\x12\x8b\x01\n" +
	"\n" +
	"UpdateRole\x12-.api.console.administration.UpdateRoleRequest\x1a+.api.console.administration.UpdateRoleReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/console/role/{id}\x12\x88\x01\n" +
	"\n" +
	"DeleteRole\x12-.api.console.administration.DeleteRoleRequest\x1a+.api.console.administration.DeleteRoleReply\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/console/role/{id}\x12\x7f\n" +
	"\aGetRole\x12*.api.console.administration.GetRoleRequest\x1a(.api.console.administration.GetRoleReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/console/role/{id}\x12}\n" +
	"\bListRole\x12+.api.console.administration.ListRoleRequest\x1a).api.console.administration.ListRoleReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/console/role\x12\xa2\x01\n" +
	"\x0eBindPermission\x121.api.console.administration.BindPermissionRequest\x1a/.api.console.administration.BindPermissionReply\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/console/role/{id}/permission\x12\xb8\x01\n" +
	"\x10UnbindPermission\x123.api.console.administration.UnbindPermissionRequest\x1a1.api.console.administration.UnbindPermissionReply\"<\x82\xd3\xe4\x93\x026:\x01*\x1a1/api/console/role/{id}/permission/{permission_id}Bk\n" +
	"\x1aapi.console.administrationP\x01ZKgithub.com/omalloc/kratos-console/api/console/administration;administrationb\x06proto3"

var (
	file_console_administration_role_proto_rawDescOnce sync.Once
	file_console_administration_role_proto_rawDescData []byte
)

func file_console_administration_role_proto_rawDescGZIP() []byte {
	file_console_administration_role_proto_rawDescOnce.Do(func() {
		file_console_administration_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_administration_role_proto_rawDesc), len(file_console_administration_role_proto_rawDesc)))
	})
	return file_console_administration_role_proto_rawDescData
}

var file_console_administration_role_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_console_administration_role_proto_goTypes = []any{
	(*RoleInfo)(nil),                // 0: api.console.administration.RoleInfo
	(*CreateRoleRequest)(nil),       // 1: api.console.administration.CreateRoleRequest
	(*CreateRoleReply)(nil),         // 2: api.console.administration.CreateRoleReply
	(*UpdateRoleRequest)(nil),       // 3: api.console.administration.UpdateRoleRequest
	(*UpdateRoleReply)(nil),         // 4: api.console.administration.UpdateRoleReply
	(*DeleteRoleRequest)(nil),       // 5: api.console.administration.DeleteRoleRequest
	(*DeleteRoleReply)(nil),         // 6: api.console.administration.DeleteRoleReply
	(*GetRoleRequest)(nil),          // 7: api.console.administration.GetRoleRequest
	(*GetRoleReply)(nil),            // 8: api.console.administration.GetRoleReply
	(*ListRoleRequest)(nil),         // 9: api.console.administration.ListRoleRequest
	(*ListRoleReply)(nil),           // 10: api.console.administration.ListRoleReply
	(*BindPermissionRequest)(nil),   // 11: api.console.administration.BindPermissionRequest
	(*BindPermissionReply)(nil),     // 12: api.console.administration.BindPermissionReply
	(*UnbindPermissionRequest)(nil), // 13: api.console.administration.UnbindPermissionRequest
	(*UnbindPermissionReply)(nil),   // 14: api.console.administration.UnbindPermissionReply
	(*Action)(nil),                  // 15: api.console.administration.Action
	(*protobuf.Pagination)(nil),     // 16: protobuf.Pagination
}
var file_console_administration_role_proto_depIdxs = []int32{
	15, // 0: api.console.administration.RoleInfo.actions:type_name -> api.console.administration.Action
	15, // 1: api.console.administration.RoleInfo.data_access:type_name -> api.console.administration.Action
	15, // 2: api.console.administration.GetRoleReply.actions:type_name -> api.console.administration.Action
	15, // 3: api.console.administration.GetRoleReply.data_access:type_name -> api.console.administration.Action
	16, // 4: api.console.administration.ListRoleRequest.pagination:type_name -> protobuf.Pagination
	16, // 5: api.console.administration.ListRoleReply.pagination:type_name -> protobuf.Pagination
	0,  // 6: api.console.administration.ListRoleReply.data:type_name -> api.console.administration.RoleInfo
	15, // 7: api.console.administration.BindPermissionRequest.actions:type_name -> api.console.administration.Action
	15, // 8: api.console.administration.BindPermissionRequest.data_access:type_name -> api.console.administration.Action
	1,  // 9: api.console.administration.Role.CreateRole:input_type -> api.console.administration.CreateRoleRequest
	3,  // 10: api.console.administration.Role.UpdateRole:input_type -> api.console.administration.UpdateRoleRequest
	5,  // 11: api.console.administration.Role.DeleteRole:input_type -> api.console.administration.DeleteRoleRequest
	7,  // 12: api.console.administration.Role.GetRole:input_type -> api.console.administration.GetRoleRequest
	9,  // 13: api.console.administration.Role.ListRole:input_type -> api.console.administration.ListRoleRequest
	11, // 14: api.console.administration.Role.BindPermission:input_type -> api.console.administration.BindPermissionRequest
	13, // 15: api.console.administration.Role.UnbindPermission:input_type -> api.console.administration.UnbindPermissionRequest
	2,  // 16: api.console.administration.Role.CreateRole:output_type -> api.console.administration.CreateRoleReply
	4,  // 17: api.console.administration.Role.UpdateRole:output_type -> api.console.administration.UpdateRoleReply
	6,  // 18: api.console.administration.Role.DeleteRole:output_type -> api.console.administration.DeleteRoleReply
	8,  // 19: api.console.administration.Role.GetRole:output_type -> api.console.administration.GetRoleReply
	10, // 20: api.console.administration.Role.ListRole:output_type -> api.console.administration.ListRoleReply
	12, // 21: api.console.administration.Role.BindPermission:output_type -> api.console.administration.BindPermissionReply
	14, // 22: api.console.administration.Role.UnbindPermission:output_type -> api.console.administration.UnbindPermissionReply
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_console_administration_role_proto_init() }
func file_console_administration_role_proto_init() {
	if File_console_administration_role_proto != nil {
		return
	}
	file_console_administration_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_administration_role_proto_rawDesc), len(file_console_administration_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_administration_role_proto_goTypes,
		DependencyIndexes: file_console_administration_role_proto_depIdxs,
		MessageInfos:      file_console_administration_role_proto_msgTypes,
	}.Build()
	File_console_administration_role_proto = out.File
	file_console_administration_role_proto_goTypes = nil
	file_console_administration_role_proto_depIdxs = nil
}
