// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: console/administration/user.proto

package administration

import (
	protobuf "github.com/omalloc/contrib/protobuf"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	// 未定义
	UserStatus_UNKNOWN UserStatus = 0
	// 正常
	UserStatus_NORMAL UserStatus = 1
	// 禁用
	UserStatus_DISABLED UserStatus = 2
	// 删除
	UserStatus_DELETED UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "NORMAL",
		2: "DISABLED",
		3: "DELETED",
	}
	UserStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"NORMAL":   1,
		"DISABLED": 2,
		"DELETED":  3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_console_administration_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_console_administration_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{0}
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        UserStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=api.console.administration.UserStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RoleIds       []int32                `protobuf:"varint,10,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_console_administration_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UNKNOWN
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserInfo) GetRoleIds() []int32 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	RePassword    string                 `protobuf:"bytes,5,opt,name=re_password,json=rePassword,proto3" json:"re_password,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	RoleIds       []string               `protobuf:"bytes,7,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_console_administration_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRePassword() string {
	if x != nil {
		return x.RePassword
	}
	return ""
}

func (x *CreateUserRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *CreateUserRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_console_administration_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	RePassword    string                 `protobuf:"bytes,5,opt,name=re_password,json=rePassword,proto3" json:"re_password,omitempty"`
	Status        UserStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=api.console.administration.UserStatus" json:"status,omitempty"`
	RoleIds       []string               `protobuf:"bytes,7,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_console_administration_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetRePassword() string {
	if x != nil {
		return x.RePassword
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UNKNOWN
}

func (x *UpdateUserRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type UpdateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReply) Reset() {
	*x = UpdateUserReply{}
	mi := &file_console_administration_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReply) ProtoMessage() {}

func (x *UpdateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReply.ProtoReflect.Descriptor instead.
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{4}
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_console_administration_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReply) Reset() {
	*x = DeleteUserReply{}
	mi := &file_console_administration_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReply) ProtoMessage() {}

func (x *DeleteUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReply.ProtoReflect.Descriptor instead.
func (*DeleteUserReply) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{6}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_console_administration_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Roles         []*RoleInfo            `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_console_administration_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserReply) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserReply) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_console_administration_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserRequest) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *protobuf.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data          []*UserInfo            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply) Reset() {
	*x = ListUserReply{}
	mi := &file_console_administration_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply) ProtoMessage() {}

func (x *ListUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply.ProtoReflect.Descriptor instead.
func (*ListUserReply) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserReply) GetPagination() *protobuf.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListUserReply) GetData() []*UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type BindRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRoleRequest) Reset() {
	*x = BindRoleRequest{}
	mi := &file_console_administration_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRoleRequest) ProtoMessage() {}

func (x *BindRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRoleRequest.ProtoReflect.Descriptor instead.
func (*BindRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{11}
}

func (x *BindRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BindRoleRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type BindRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRoleReply) Reset() {
	*x = BindRoleReply{}
	mi := &file_console_administration_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRoleReply) ProtoMessage() {}

func (x *BindRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRoleReply.ProtoReflect.Descriptor instead.
func (*BindRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{12}
}

type UnbindRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindRoleRequest) Reset() {
	*x = UnbindRoleRequest{}
	mi := &file_console_administration_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRoleRequest) ProtoMessage() {}

func (x *UnbindRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRoleRequest.ProtoReflect.Descriptor instead.
func (*UnbindRoleRequest) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{13}
}

func (x *UnbindRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnbindRoleRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UnbindRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindRoleReply) Reset() {
	*x = UnbindRoleReply{}
	mi := &file_console_administration_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRoleReply) ProtoMessage() {}

func (x *UnbindRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_administration_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRoleReply.ProtoReflect.Descriptor instead.
func (*UnbindRoleReply) Descriptor() ([]byte, []int) {
	return file_console_administration_user_proto_rawDescGZIP(), []int{14}
}

var File_console_administration_user_proto protoreflect.FileDescriptor

const file_console_administration_user_proto_rawDesc = "" +
	"\n" +
	"!console/administration/user.proto\x12\x1aapi.console.administration\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19protobuf/pagination.proto\x1a!console/administration/role.proto\"\xd1\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12>\n" +
	"\x06status\x18\x06 \x01(\x0e2&.api.console.administration.UserStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\brole_ids\x18\n" +
	" \x03(\x05R\aroleIds\"\xd5\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1f\n" +
	"\vre_password\x18\x05 \x01(\tR\n" +
	"rePassword\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12\x19\n" +
	"\brole_ids\x18\a \x03(\tR\aroleIds\"!\n" +
	"\x0fCreateUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xed\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1f\n" +
	"\vre_password\x18\x05 \x01(\tR\n" +
	"rePassword\x12>\n" +
	"\x06status\x18\x06 \x01(\x0e2&.api.console.administration.UserStatusR\x06status\x12\x19\n" +
	"\brole_ids\x18\a \x03(\tR\aroleIds\"\x11\n" +
	"\x0fUpdateUserReply\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteUserReply\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x84\x01\n" +
	"\fGetUserReply\x128\n" +
	"\x04user\x18\x01 \x01(\v2$.api.console.administration.UserInfoR\x04user\x12:\n" +
	"\x05roles\x18\x02 \x03(\v2$.api.console.administration.RoleInfoR\x05roles\"G\n" +
	"\x0fListUserRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\"\x7f\n" +
	"\rListUserReply\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.protobuf.PaginationR\n" +
	"pagination\x128\n" +
	"\x04data\x18\x02 \x03(\v2$.api.console.administration.UserInfoR\x04data\":\n" +
	"\x0fBindRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\x0f\n" +
	"\rBindRoleReply\"<\n" +
	"\x11UnbindRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\x11\n" +
	"\x0fUnbindRoleReply*@\n" +
	"\n" +
	"UserStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x032\xcf\a\n" +
	"\x04User\x12\x86\x01\n" +
	"\n" +
	"CreateUser\x12-.api.console.administration.CreateUserRequest\x1a+.api.console.administration.CreateUserReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/console/user\x12\x8b\x01\n" +
	"\n" +
	"UpdateUser\x12-.api.console.administration.UpdateUserRequest\x1a+.api.console.administration.UpdateUserReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/console/user/{id}\x12\x88\x01\n" +
	"\n" +
	"DeleteUser\x12-.api.console.administration.DeleteUserRequest\x1a+.api.console.administration.DeleteUserReply\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/console/user/{id}\x12\x7f\n" +
	"\aGetUser\x12*.api.console.administration.GetUserRequest\x1a(.api.console.administration.GetUserReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/console/user/{id}\x12}\n" +
	"\bListUser\x12+.api.console.administration.ListUserRequest\x1a).api.console.administration.ListUserReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/console/user\x12\x8a\x01\n" +
	"\bBindRole\x12+.api.console.administration.BindRoleRequest\x1a).api.console.administration.BindRoleReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/console/user/{id}/role\x12\x97\x01\n" +
	"\n" +
	"UnbindRole\x12-.api.console.administration.UnbindRoleRequest\x1a+.api.console.administration.UnbindRoleReply\"-\x82\xd3\xe4\x93\x02'*%/api/console/user/{id}/role/{role_id}Bk\n" +
	"\x1aapi.console.administrationP\x01ZKgithub.com/omalloc/kratos-console/api/console/administration;administrationb\x06proto3"

var (
	file_console_administration_user_proto_rawDescOnce sync.Once
	file_console_administration_user_proto_rawDescData []byte
)

func file_console_administration_user_proto_rawDescGZIP() []byte {
	file_console_administration_user_proto_rawDescOnce.Do(func() {
		file_console_administration_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_administration_user_proto_rawDesc), len(file_console_administration_user_proto_rawDesc)))
	})
	return file_console_administration_user_proto_rawDescData
}

var file_console_administration_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_console_administration_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_console_administration_user_proto_goTypes = []any{
	(UserStatus)(0),               // 0: api.console.administration.UserStatus
	(*UserInfo)(nil),              // 1: api.console.administration.UserInfo
	(*CreateUserRequest)(nil),     // 2: api.console.administration.CreateUserRequest
	(*CreateUserReply)(nil),       // 3: api.console.administration.CreateUserReply
	(*UpdateUserRequest)(nil),     // 4: api.console.administration.UpdateUserRequest
	(*UpdateUserReply)(nil),       // 5: api.console.administration.UpdateUserReply
	(*DeleteUserRequest)(nil),     // 6: api.console.administration.DeleteUserRequest
	(*DeleteUserReply)(nil),       // 7: api.console.administration.DeleteUserReply
	(*GetUserRequest)(nil),        // 8: api.console.administration.GetUserRequest
	(*GetUserReply)(nil),          // 9: api.console.administration.GetUserReply
	(*ListUserRequest)(nil),       // 10: api.console.administration.ListUserRequest
	(*ListUserReply)(nil),         // 11: api.console.administration.ListUserReply
	(*BindRoleRequest)(nil),       // 12: api.console.administration.BindRoleRequest
	(*BindRoleReply)(nil),         // 13: api.console.administration.BindRoleReply
	(*UnbindRoleRequest)(nil),     // 14: api.console.administration.UnbindRoleRequest
	(*UnbindRoleReply)(nil),       // 15: api.console.administration.UnbindRoleReply
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*RoleInfo)(nil),              // 17: api.console.administration.RoleInfo
	(*protobuf.Pagination)(nil),   // 18: protobuf.Pagination
}
var file_console_administration_user_proto_depIdxs = []int32{
	0,  // 0: api.console.administration.UserInfo.status:type_name -> api.console.administration.UserStatus
	16, // 1: api.console.administration.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: api.console.administration.UserInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: api.console.administration.UpdateUserRequest.status:type_name -> api.console.administration.UserStatus
	1,  // 4: api.console.administration.GetUserReply.user:type_name -> api.console.administration.UserInfo
	17, // 5: api.console.administration.GetUserReply.roles:type_name -> api.console.administration.RoleInfo
	18, // 6: api.console.administration.ListUserRequest.pagination:type_name -> protobuf.Pagination
	18, // 7: api.console.administration.ListUserReply.pagination:type_name -> protobuf.Pagination
	1,  // 8: api.console.administration.ListUserReply.data:type_name -> api.console.administration.UserInfo
	2,  // 9: api.console.administration.User.CreateUser:input_type -> api.console.administration.CreateUserRequest
	4,  // 10: api.console.administration.User.UpdateUser:input_type -> api.console.administration.UpdateUserRequest
	6,  // 11: api.console.administration.User.DeleteUser:input_type -> api.console.administration.DeleteUserRequest
	8,  // 12: api.console.administration.User.GetUser:input_type -> api.console.administration.GetUserRequest
	10, // 13: api.console.administration.User.ListUser:input_type -> api.console.administration.ListUserRequest
	12, // 14: api.console.administration.User.BindRole:input_type -> api.console.administration.BindRoleRequest
	14, // 15: api.console.administration.User.UnbindRole:input_type -> api.console.administration.UnbindRoleRequest
	3,  // 16: api.console.administration.User.CreateUser:output_type -> api.console.administration.CreateUserReply
	5,  // 17: api.console.administration.User.UpdateUser:output_type -> api.console.administration.UpdateUserReply
	7,  // 18: api.console.administration.User.DeleteUser:output_type -> api.console.administration.DeleteUserReply
	9,  // 19: api.console.administration.User.GetUser:output_type -> api.console.administration.GetUserReply
	11, // 20: api.console.administration.User.ListUser:output_type -> api.console.administration.ListUserReply
	13, // 21: api.console.administration.User.BindRole:output_type -> api.console.administration.BindRoleReply
	15, // 22: api.console.administration.User.UnbindRole:output_type -> api.console.administration.UnbindRoleReply
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_console_administration_user_proto_init() }
func file_console_administration_user_proto_init() {
	if File_console_administration_user_proto != nil {
		return
	}
	file_console_administration_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_administration_user_proto_rawDesc), len(file_console_administration_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_administration_user_proto_goTypes,
		DependencyIndexes: file_console_administration_user_proto_depIdxs,
		EnumInfos:         file_console_administration_user_proto_enumTypes,
		MessageInfos:      file_console_administration_user_proto_msgTypes,
	}.Build()
	File_console_administration_user_proto = out.File
	file_console_administration_user_proto_goTypes = nil
	file_console_administration_user_proto_depIdxs = nil
}
