// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: console/passport/passport.proto

package passport

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	administration "github.com/omalloc/kratos-admin/api/console/administration"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// Set the error code separately for an enumeration.
	ErrorReason_USER_NOT_FOUND         ErrorReason = 0
	ErrorReason_USER_OR_PASSWORD_ERROR ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "USER_OR_PASSWORD_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":         0,
		"USER_OR_PASSWORD_ERROR": 1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_console_passport_passport_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_console_passport_passport_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{0}
}

type CaptchaType int32

const (
	CaptchaType_CAPTCHA_TYPE_UNSPECIFIED CaptchaType = 0
	CaptchaType_CAPTCHA_TYPE_EMAIL       CaptchaType = 1
	CaptchaType_CAPTCHA_TYPE_SMS         CaptchaType = 2
)

// Enum value maps for CaptchaType.
var (
	CaptchaType_name = map[int32]string{
		0: "CAPTCHA_TYPE_UNSPECIFIED",
		1: "CAPTCHA_TYPE_EMAIL",
		2: "CAPTCHA_TYPE_SMS",
	}
	CaptchaType_value = map[string]int32{
		"CAPTCHA_TYPE_UNSPECIFIED": 0,
		"CAPTCHA_TYPE_EMAIL":       1,
		"CAPTCHA_TYPE_SMS":         2,
	}
)

func (x CaptchaType) Enum() *CaptchaType {
	p := new(CaptchaType)
	*p = x
	return p
}

func (x CaptchaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptchaType) Descriptor() protoreflect.EnumDescriptor {
	return file_console_passport_passport_proto_enumTypes[1].Descriptor()
}

func (CaptchaType) Type() protoreflect.EnumType {
	return &file_console_passport_passport_proto_enumTypes[1]
}

func (x CaptchaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptchaType.Descriptor instead.
func (CaptchaType) EnumDescriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{1}
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 自动登录
	AutoLogin     bool `protobuf:"varint,3,opt,name=auto_login,json=autoLogin,proto3" json:"auto_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetAutoLogin() bool {
	if x != nil {
		return x.AutoLogin
	}
	return false
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_console_passport_passport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{1}
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{2}
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_console_passport_passport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 验证码
	Captcha       string `protobuf:"bytes,5,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_console_passport_passport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{5}
}

type SendCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CaptchaType            `protobuf:"varint,1,opt,name=type,proto3,enum=api.console.passport.CaptchaType" json:"type,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCaptchaRequest) Reset() {
	*x = SendCaptchaRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCaptchaRequest) ProtoMessage() {}

func (x *SendCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCaptchaRequest.ProtoReflect.Descriptor instead.
func (*SendCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{6}
}

func (x *SendCaptchaRequest) GetType() CaptchaType {
	if x != nil {
		return x.Type
	}
	return CaptchaType_CAPTCHA_TYPE_UNSPECIFIED
}

func (x *SendCaptchaRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type SendCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCaptchaReply) Reset() {
	*x = SendCaptchaReply{}
	mi := &file_console_passport_passport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCaptchaReply) ProtoMessage() {}

func (x *SendCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCaptchaReply.ProtoReflect.Descriptor instead.
func (*SendCaptchaReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{7}
}

type SendResetPasswordCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResetPasswordCaptchaRequest) Reset() {
	*x = SendResetPasswordCaptchaRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResetPasswordCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResetPasswordCaptchaRequest) ProtoMessage() {}

func (x *SendResetPasswordCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResetPasswordCaptchaRequest.ProtoReflect.Descriptor instead.
func (*SendResetPasswordCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{8}
}

func (x *SendResetPasswordCaptchaRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendResetPasswordCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResetPasswordCaptchaReply) Reset() {
	*x = SendResetPasswordCaptchaReply{}
	mi := &file_console_passport_passport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResetPasswordCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResetPasswordCaptchaReply) ProtoMessage() {}

func (x *SendResetPasswordCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResetPasswordCaptchaReply.ProtoReflect.Descriptor instead.
func (*SendResetPasswordCaptchaReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{9}
}

type ResetPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 重置密码令牌
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// 密码
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{10}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReply) Reset() {
	*x = ResetPasswordReply{}
	mi := &file_console_passport_passport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReply) ProtoMessage() {}

func (x *ResetPasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReply.ProtoReflect.Descriptor instead.
func (*ResetPasswordReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{11}
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUsernameRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUsernameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameReply) Reset() {
	*x = UpdateUsernameReply{}
	mi := &file_console_passport_passport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameReply) ProtoMessage() {}

func (x *UpdateUsernameReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameReply.ProtoReflect.Descriptor instead.
func (*UpdateUsernameReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{13}
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReply) Reset() {
	*x = UpdateProfileReply{}
	mi := &file_console_passport_passport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReply) ProtoMessage() {}

func (x *UpdateProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReply.ProtoReflect.Descriptor instead.
func (*UpdateProfileReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{15}
}

type CurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserRequest) Reset() {
	*x = CurrentUserRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserRequest) ProtoMessage() {}

func (x *CurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserRequest.ProtoReflect.Descriptor instead.
func (*CurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{16}
}

type CurrentUserReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	User          *administration.UserInfo   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Roles         []*administration.RoleInfo `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserReply) Reset() {
	*x = CurrentUserReply{}
	mi := &file_console_passport_passport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserReply) ProtoMessage() {}

func (x *CurrentUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserReply.ProtoReflect.Descriptor instead.
func (*CurrentUserReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{17}
}

func (x *CurrentUserReply) GetUser() *administration.UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CurrentUserReply) GetRoles() []*administration.RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AuthorizeMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeMenuRequest) Reset() {
	*x = AuthorizeMenuRequest{}
	mi := &file_console_passport_passport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeMenuRequest) ProtoMessage() {}

func (x *AuthorizeMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeMenuRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeMenuRequest) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{18}
}

func (x *AuthorizeMenuRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AuthorizeMenuReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*administration.MenuInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeMenuReply) Reset() {
	*x = AuthorizeMenuReply{}
	mi := &file_console_passport_passport_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeMenuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeMenuReply) ProtoMessage() {}

func (x *AuthorizeMenuReply) ProtoReflect() protoreflect.Message {
	mi := &file_console_passport_passport_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeMenuReply.ProtoReflect.Descriptor instead.
func (*AuthorizeMenuReply) Descriptor() ([]byte, []int) {
	return file_console_passport_passport_proto_rawDescGZIP(), []int{19}
}

func (x *AuthorizeMenuReply) GetData() []*administration.MenuInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_console_passport_passport_proto protoreflect.FileDescriptor

const file_console_passport_passport_proto_rawDesc = "" +
	"\n" +
	"\x1fconsole/passport/passport.proto\x12\x14api.console.passport\x1a\x13errors/errors.proto\x1a\x1cgoogle/api/annotations.proto\x1a!console/administration/user.proto\x1a!console/administration/role.proto\x1a!console/administration/menu.proto\"e\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"auto_login\x18\x03 \x01(\bR\tautoLogin\"\f\n" +
	"\n" +
	"LoginReply\"\x0f\n" +
	"\rLogoutRequest\"\r\n" +
	"\vLogoutReply\"\x95\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\acaptcha\x18\x05 \x01(\tR\acaptcha\"\x0f\n" +
	"\rRegisterReply\"_\n" +
	"\x12SendCaptchaRequest\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.api.console.passport.CaptchaTypeR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\"\x12\n" +
	"\x10SendCaptchaReply\"7\n" +
	"\x1fSendResetPasswordCaptchaRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x1f\n" +
	"\x1dSendResetPasswordCaptchaReply\"^\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x14\n" +
	"\x12ResetPasswordReply\"C\n" +
	"\x15UpdateUsernameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x15\n" +
	"\x13UpdateUsernameReply\"\\\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"\x14\n" +
	"\x12UpdateProfileReply\"\x14\n" +
	"\x12CurrentUserRequest\"\x88\x01\n" +
	"\x10CurrentUserReply\x128\n" +
	"\x04user\x18\x01 \x01(\v2$.api.console.administration.UserInfoR\x04user\x12:\n" +
	"\x05roles\x18\x02 \x03(\v2$.api.console.administration.RoleInfoR\x05roles\"/\n" +
	"\x14AuthorizeMenuRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\x12AuthorizeMenuReply\x128\n" +
	"\x04data\x18\x01 \x03(\v2$.api.console.administration.MenuInfoR\x04data*O\n" +
	"\vErrorReason\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12 \n" +
	"\x16USER_OR_PASSWORD_ERROR\x10\x01\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03*Y\n" +
	"\vCaptchaType\x12\x1c\n" +
	"\x18CAPTCHA_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CAPTCHA_TYPE_EMAIL\x10\x01\x12\x14\n" +
	"\x10CAPTCHA_TYPE_SMS\x10\x022\xae\v\n" +
	"\bPassport\x12u\n" +
	"\x05Login\x12\".api.console.passport.LoginRequest\x1a .api.console.passport.LoginReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/console/passport/login\x12y\n" +
	"\x06Logout\x12#.api.console.passport.LogoutRequest\x1a!.api.console.passport.LogoutReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/console/passport/logout\x12\x81\x01\n" +
	"\bRegister\x12%.api.console.passport.RegisterRequest\x1a#.api.console.passport.RegisterReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/console/passport/register\x12\x8e\x01\n" +
	"\vSendCaptcha\x12(.api.console.passport.SendCaptchaRequest\x1a&.api.console.passport.SendCaptchaReply\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/console/passport/send_captcha\x12\xb5\x01\n" +
	"\x11SendResetPassword\x125.api.console.passport.SendResetPasswordCaptchaRequest\x1a3.api.console.passport.SendResetPasswordCaptchaReply\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/console/passport/send_reset_password\x12\x96\x01\n" +
	"\rResetPassword\x12*.api.console.passport.ResetPasswordRequest\x1a(.api.console.passport.ResetPasswordReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/console/passport/reset_password\x12\x98\x01\n" +
	"\x0eUpdateUsername\x12+.api.console.passport.UpdateUsernameRequest\x1a).api.console.passport.UpdateUsernameReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/console/passport/{id}/username\x12\x8f\x01\n" +
	"\rUpdateProfile\x12*.api.console.passport.UpdateProfileRequest\x1a(.api.console.passport.UpdateProfileReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/console/passport/profile\x12\x86\x01\n" +
	"\vCurrentUser\x12(.api.console.passport.CurrentUserRequest\x1a&.api.console.passport.CurrentUserReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/console/passport/current\x12\x93\x01\n" +
	"\rAuthorizeMenu\x12*.api.console.passport.AuthorizeMenuRequest\x1a(.api.console.passport.AuthorizeMenuReply\",\x82\xd3\xe4\x93\x02&\x12$/api/console/passport/authorize_menuBW\n" +
	"\x14api.console.passportP\x01Z=github.com/omalloc/kratos-admin/api/console/passport;passportb\x06proto3"

var (
	file_console_passport_passport_proto_rawDescOnce sync.Once
	file_console_passport_passport_proto_rawDescData []byte
)

func file_console_passport_passport_proto_rawDescGZIP() []byte {
	file_console_passport_passport_proto_rawDescOnce.Do(func() {
		file_console_passport_passport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_passport_passport_proto_rawDesc), len(file_console_passport_passport_proto_rawDesc)))
	})
	return file_console_passport_passport_proto_rawDescData
}

var file_console_passport_passport_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_console_passport_passport_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_console_passport_passport_proto_goTypes = []any{
	(ErrorReason)(0),                        // 0: api.console.passport.ErrorReason
	(CaptchaType)(0),                        // 1: api.console.passport.CaptchaType
	(*LoginRequest)(nil),                    // 2: api.console.passport.LoginRequest
	(*LoginReply)(nil),                      // 3: api.console.passport.LoginReply
	(*LogoutRequest)(nil),                   // 4: api.console.passport.LogoutRequest
	(*LogoutReply)(nil),                     // 5: api.console.passport.LogoutReply
	(*RegisterRequest)(nil),                 // 6: api.console.passport.RegisterRequest
	(*RegisterReply)(nil),                   // 7: api.console.passport.RegisterReply
	(*SendCaptchaRequest)(nil),              // 8: api.console.passport.SendCaptchaRequest
	(*SendCaptchaReply)(nil),                // 9: api.console.passport.SendCaptchaReply
	(*SendResetPasswordCaptchaRequest)(nil), // 10: api.console.passport.SendResetPasswordCaptchaRequest
	(*SendResetPasswordCaptchaReply)(nil),   // 11: api.console.passport.SendResetPasswordCaptchaReply
	(*ResetPasswordRequest)(nil),            // 12: api.console.passport.ResetPasswordRequest
	(*ResetPasswordReply)(nil),              // 13: api.console.passport.ResetPasswordReply
	(*UpdateUsernameRequest)(nil),           // 14: api.console.passport.UpdateUsernameRequest
	(*UpdateUsernameReply)(nil),             // 15: api.console.passport.UpdateUsernameReply
	(*UpdateProfileRequest)(nil),            // 16: api.console.passport.UpdateProfileRequest
	(*UpdateProfileReply)(nil),              // 17: api.console.passport.UpdateProfileReply
	(*CurrentUserRequest)(nil),              // 18: api.console.passport.CurrentUserRequest
	(*CurrentUserReply)(nil),                // 19: api.console.passport.CurrentUserReply
	(*AuthorizeMenuRequest)(nil),            // 20: api.console.passport.AuthorizeMenuRequest
	(*AuthorizeMenuReply)(nil),              // 21: api.console.passport.AuthorizeMenuReply
	(*administration.UserInfo)(nil),         // 22: api.console.administration.UserInfo
	(*administration.RoleInfo)(nil),         // 23: api.console.administration.RoleInfo
	(*administration.MenuInfo)(nil),         // 24: api.console.administration.MenuInfo
}
var file_console_passport_passport_proto_depIdxs = []int32{
	1,  // 0: api.console.passport.SendCaptchaRequest.type:type_name -> api.console.passport.CaptchaType
	22, // 1: api.console.passport.CurrentUserReply.user:type_name -> api.console.administration.UserInfo
	23, // 2: api.console.passport.CurrentUserReply.roles:type_name -> api.console.administration.RoleInfo
	24, // 3: api.console.passport.AuthorizeMenuReply.data:type_name -> api.console.administration.MenuInfo
	2,  // 4: api.console.passport.Passport.Login:input_type -> api.console.passport.LoginRequest
	4,  // 5: api.console.passport.Passport.Logout:input_type -> api.console.passport.LogoutRequest
	6,  // 6: api.console.passport.Passport.Register:input_type -> api.console.passport.RegisterRequest
	8,  // 7: api.console.passport.Passport.SendCaptcha:input_type -> api.console.passport.SendCaptchaRequest
	10, // 8: api.console.passport.Passport.SendResetPassword:input_type -> api.console.passport.SendResetPasswordCaptchaRequest
	12, // 9: api.console.passport.Passport.ResetPassword:input_type -> api.console.passport.ResetPasswordRequest
	14, // 10: api.console.passport.Passport.UpdateUsername:input_type -> api.console.passport.UpdateUsernameRequest
	16, // 11: api.console.passport.Passport.UpdateProfile:input_type -> api.console.passport.UpdateProfileRequest
	18, // 12: api.console.passport.Passport.CurrentUser:input_type -> api.console.passport.CurrentUserRequest
	20, // 13: api.console.passport.Passport.AuthorizeMenu:input_type -> api.console.passport.AuthorizeMenuRequest
	3,  // 14: api.console.passport.Passport.Login:output_type -> api.console.passport.LoginReply
	5,  // 15: api.console.passport.Passport.Logout:output_type -> api.console.passport.LogoutReply
	7,  // 16: api.console.passport.Passport.Register:output_type -> api.console.passport.RegisterReply
	9,  // 17: api.console.passport.Passport.SendCaptcha:output_type -> api.console.passport.SendCaptchaReply
	11, // 18: api.console.passport.Passport.SendResetPassword:output_type -> api.console.passport.SendResetPasswordCaptchaReply
	13, // 19: api.console.passport.Passport.ResetPassword:output_type -> api.console.passport.ResetPasswordReply
	15, // 20: api.console.passport.Passport.UpdateUsername:output_type -> api.console.passport.UpdateUsernameReply
	17, // 21: api.console.passport.Passport.UpdateProfile:output_type -> api.console.passport.UpdateProfileReply
	19, // 22: api.console.passport.Passport.CurrentUser:output_type -> api.console.passport.CurrentUserReply
	21, // 23: api.console.passport.Passport.AuthorizeMenu:output_type -> api.console.passport.AuthorizeMenuReply
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_console_passport_passport_proto_init() }
func file_console_passport_passport_proto_init() {
	if File_console_passport_passport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_passport_passport_proto_rawDesc), len(file_console_passport_passport_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_passport_passport_proto_goTypes,
		DependencyIndexes: file_console_passport_passport_proto_depIdxs,
		EnumInfos:         file_console_passport_passport_proto_enumTypes,
		MessageInfos:      file_console_passport_passport_proto_msgTypes,
	}.Build()
	File_console_passport_passport_proto = out.File
	file_console_passport_passport_proto_goTypes = nil
	file_console_passport_passport_proto_depIdxs = nil
}
